version: '3'
services:
  web:
    hostname: web-contact
    container_name: web-contact
    build: .
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/
    depends_on:
      - db
  db:
    hostname: db-contact
    container_name: db-contact
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d/:ro