<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Id</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Birthdate</th>
            <th>Phone</th>
            <th style="width: 100px"></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $contact): ?>
            <tr>
                <td><?php echo $contact->getId() ?></td>
                <td><?php echo $contact->getFirstName() ?></td>
                <td><?php echo $contact->getLastName() ?></td>
                <td><?php echo $contact->getEmail() ?></td>
                <td><?php echo $contact->getBirthdate() ?></td>
                <td><?php echo $contact->getPhone() ?></td>

                <td>
                    <div class="btn-group">
                        <a href="<?php echo '/contacts/edit/' . $contact->getId() ?>"
                           class="btn btn-outline-secondary">Edit</a>
                        <button type="button" class="btn btn-outline-secondary dropdown-toggle dropdown-toggle-split"
                                data-toggle="dropdown">
                        </button>
                        <div class="dropdown-menu dropdown-menu-right">
                            <a class="dropdown-item"
                               href="<?php echo '/contacts/delete/' . $contact->getId() ?>">Delete</a>
                        </div>
                    </div>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo(["contacts/search", "First", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["contacts/search?page=" . $page->before, "Previous", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["contacts/search?page=" . $page->next, "Next", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["contacts/search?page=" . $page->last, "Last", 'class' => 'page-link']) ?></li>
            </ul>
        </nav>
    </div>
</div>
